### ISSUE TITLE
camera_settings.json;object_settings.json

### ISSUE THREAD

**Issue by Ysh1n3** [fraunhoferhhi/casapose#2]
May I ask how to obtain these files？

Is using dataset_ Converter. py? If so, how should I use it?

 We look forward to your reply

**Comment by gard-n** [comment]
Dear Ysh1n3,

yes, the files are obtained by using the `util_scripts/dataset_converter.py`. The script converts data generated with BlenderProc to a compatible format.  An explanation how to create a suitable dataset with BlenderProc can be found [here](https://github.com/DLR-RM/BlenderProc/blob/3f40e88b72f272a1d3159849e651d690521f2aae/examples/datasets/bop_challenge/README.mdd).
For customized datasets, only one instance should be visible per object per image.

Alternatively you can create a custom dataset using [NNDS](https://github.com/NVIDIA/Dataset_Synthesizer). NDDS directly generates `camera_settings.json` and `object_settings.json`, but the configuration of a synthetic scene might be more complicated than with BlenderProc.

Best regards
Niklas

**Comment by Ysh1n3** [comment]
Thank you! The problem has been resolved.
