### ISSUE TITLE
test code run on cpu 

### ISSUE THREAD

**Issue by assia855** [fraunhoferhhi/casapose#3]
Hello, 
thanks for sharing your work. I would like to test  it but I don't know why it keeps running on cpus and not the gpu. Thanks in advance.

**Comment by gard-n** [comment]
Hello assia855, 

Thank you for your interest in our work. Please make sure, that in the config file (e.g. `config_8.ini`) the parameter `gpuids` points to the ID of the GPU you want to use and that this GPU is supported by your TensorFlow version.  You can use the following code snippet to confirm whether your GPU is recognized by TensorFlow:

```python
import tensorflow as tf
tf.config.list_physical_devices('GPU')
```

We have tested our code on both Windows and Ubuntu, and GPU execution should be the default behavior. 

Best regards,
Niklas
