### ISSUE TITLE
Example running

### ISSUE THREAD

**Issue by kordou** [fraunhoferhhi/casapose#4]
HI,
Thnak you for your code.

i am a student in ML (just started) in a master degree and a have an assigment to run a POSE6D code. 
i managed to install yours and run the 
python test_casapose.py -c config/config_8.ini --load_h5_weights 1 --load_h5_filename ../../../data/pretrained_models/result_w_8 --datatest $DATAPATH/lmo/test --datameshes $DATAPATH/lmo/models --train_vectors_with_ground_truth 0

i would like to ask if there is a way to use it with camera somehow ? 
or with an image at least and see the object bounding box

and if thre is any way to run it on google colab in order to use the cude beacuse in my setup it does not recognize it even in if have installed the 11.3 and my card supports it

i am running on a win11 setup

thank you dor youw help

**Comment by ronnypollak** [comment]
Hello, I am also a student who recently started to work on 6d pose estimation. I wanted to ask you about your progression and if you could provide me with some information? Thank you.

**Comment by gard-n** [comment]
Dear kordou, dear ronnypollak, 

I am sorry, currently there is no code to use CASAPose with a webcam. However, it should not be difficult to program it yourself using parts of the code from my repo and `opencv` to capture images from a webcam.

You could use the script `util_scripts/test_minimal.py `as a starting point. The` ImageOnlyDataset` basically only loads Images from a folder, so this could be replaced by your own Webcam images. Then take a look at `draw_utils.py` (e.g. `draw_bb`) and `dataset_utils.py` (e.g. `save_poses_single_sample`), where you can find functions for drawing the detection in your input image, which you can use as a guide when creating your own drawing function.

Additionally you may take a look at the code of [this](https://github.com/mon203/w251_final_project/tree/main) repository, where a group of students from the University of California, Berkeley used my code in a research project and as far I know also implemented webcam usage. However, I don't know any specific details about their code.

I wish both of you good luck with your projects!

**Comment by ronnypollak** [comment]
Thank you very much for your quick answer @gard-n!
I will definitely look into the mentioned points.
I was wondering if I could DM you somewhere regarding my project, because you seem to have a lot of knowledge on the topic and maybe you could help me answer some of my questions, if you would be open to that?

**Comment by gard-n** [comment]
Yes, feel free to DM me. Happy to help.
