### ISSUE TITLE
Models files missing at BASE_URL

### ISSUE THREAD

**Issue by sswetonicdino** [fraunhoferhhi/casapose#5]
In prepare_data.py:
The model files are missing at the https://bop.felk.cvut.cz/media/data/bop_datasets/ URL.

They should be available at https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/ but the script will need to be modified i.e. 

lm stuff is at https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/lm

lmo stuff is at https://huggingface.co/datasets/bop-benchmark/datasets/resolve/main/lmo

**Comment by gard-n** [comment]
Hey sswetonicdino,

thank you for reporting this. Unfortunately, the links you provided do not work either. I hope the Bop website is only temporarily down, perhaps due to preparations for this year's challenge. It was still available a few days ago. I'll check it again in the next days.

**Comment by gard-n** [comment]
I have changed the URLs to the ones you specified as they are now working again.
Everything should work as intended again.
